### ISSUE TITLE
Literature to engage

### ISSUE THREAD

**Issue by fsolt** [fsolt/dcpo_gayrights#3]
Consider ["The Evolution of Attitudes on Same-Sex Marriage in the United States, 1988–2014"](https://onlinelibrary.wiley.com/doi/10.1111/ssqu.12673)

**Comment by casstai** [comment]
A Cross-National Study of the Legality of Homosexual Acts https://journals.sagepub.com/doi/abs/10.1177/0010414012453693

**Comment by fsolt** [comment]
[Tara Gonsalves. 2021. "Transnational Diffusion and Regional Resistance: Domestic LGBT Association Founding, 1979–2009." Social Forces 99(4):1601–1630](https://academic.oup.com/sf/article-abstract/99/4/1601/5881840) [UIowa link](http://proxy.lib.uiowa.edu/login?url=https://academic.oup.com/sf/article-abstract/99/4/1601/5881840)
(Already [listed in diffusion piece](https://github.com/fsolt/diffusion_tolerance/issues/3#issuecomment-1022769526))

**Comment by fsolt** [comment]
[Public attitudes about emergent issues in LGBTQ rights: Conversion therapy and religious refusals ](https://journals.sagepub.com/doi/full/10.1177/2053168020966874?utm_source=selligent&utm_medium=email&utm_campaign=&utm_content=&utm_term=&M_BT=26948550502641)

**Comment by fsolt** [comment]
[Kreitzer RJ, Hamilton AJ, Tolbert CJ. Does Policy Adoption Change Opinions on Minority Rights? The Effects of Legalizing Same-Sex Marriage. Political Research Quarterly. 2014;67(4):795-808](https://doi.org/10.1177/1065912914540483)

**Comment by fsolt** [comment]
@sammo3182: attitudes towards homosexuality is a key post-material attitude and therefore is evidence of the extent of modernization of countries (per Inglehart et al.).  Even those who are not super-interested in the exact topic should be interested on these grounds, i.e., human flourishing per Welzel.  See also the UN's Sustainable Development Goals (or other IO output) regarding human rights and similar.

**Comment by hey-ikon** [comment]
** policy/political decisions & public opinion 
- [The Effect of a Supreme Court Decision Regarding Gay Marriage on Social Norms and Personal Attitudes](https://journals.sagepub.com/doi/pdf/10.1177/0956797617709594?casa_token=6Y8zbtanWKIAAAAA:YLvejrEopVG4iXzHi0-qemS-wln-PwibNdZv2gd7ZPLtLEYt_WhBCfootGEOzJx65BgK4aRoMBkV)
- [Backlash, Consensus, Legitimacy, or Polarization: The Effect of Same-Sex Marriage Policy on Mass Attitudes](https://journals.sagepub.com/doi/pdf/10.1177/1065912915621175?casa_token=H3AhLU8ZZroAAAAA:ym2m7KTzDNB0HcfMcLtyupT0-6ZQKRFdaDC3J1TxycfXjzS87pf26GUL9ul9xEVKsdRvDXx3Vufl)

** across time and space 
- [Historical and Contemporary Attitudes Toward Homosexuality](https://journals.sagepub.com/doi/full/10.1177/0098628316636297?casa_token=0ZYCiGrKiSIAAAAA:Mg8E-bHJu68_ISFcuyzP4vk5ohHHlihNNDIYqq37RGsHgSggBHxoatK0hkfOpPODUI-60MXM5O9c)
- [Examining Public Opinion About LGBTQ-Related Issues in the United States and Across Multiple Nations](https://www.annualreviews.org/doi/abs/10.1146/annurev-soc-073018-022332?casa_token=73b5hnPB9p8AAAAA%3AYFi61aIpC5wUqcLmwDNu_TTTImGZi0VV6LTt3yuWk1ZlrDwlgoJlAsHlnxt9rOU5twp12bTzDLXW&journalCode=soc)
- [Public Attitudes towards Homosexuality and Gay Rights across Time and Countries](https://escholarship.org/content/qt4p93w90c/qt4p93w90c.pdf)
- [Cross-Cultural Psychology Contemporary Themes and Perspectives](https://d1wqtxts1xzle7.cloudfront.net/38451764/libro_de_texto_Keith-with-cover-page-v2.pdf?Expires=1667361954&Signature=T9FRFXpoUPUM3~oa433x8xM9RVmFxe~kZH0Q-D4nrCgDSAe17xmbGNBqQPvldfVIF7Q0~aeRqIMwQ0CsOjU9uHtosW5bGXNGHuo4Qg4sB~CrpvkBn~q5pisx956cCcit2~tLC6S89dB4-69C7l0NYflqStxDJHuMbm6DJHLrzgWTVFGmhZxCgZok2GXtwEPRDe5jFyFiaJ~GYNpAHs4MWYPrNnhczOCAchO0b9r3Szep3iuWuCdo06KB6XQldJjVVSPSRI--buyq4Kcf4haXhQQbdRfx52jDFPvEh-ne3ToJ3aYRmy66QV6d4rX2gX~PraW2iW0zViNxQlartyjjeA__&Key-Pair-Id=APKAJLOHF5GGSLRBV4ZA) -- Chapter 12. Experiences of Sexual Minorities in Diverse Cultures (pp.235-256)
- [Gendered Trajectories to Tolerance: Men’s and Women’s Changing Attitudes toward Homosexuality in Japan, 1981–2019](https://www.tandfonline.com/doi/full/10.1080/00918369.2022.2095243)
- [Social Tolerance of Homosexuality: A Quantitative Comparison of Mainland China, Singapore, and Taiwan](https://www.tandfonline.com/doi/pdf/10.1080/21620555.2019.1654368?casa_token=TF8cKEQjvi0AAAAA:zEdn4I0INsCHFM-Nc-7uZHR1O9kXTLkl_7-5BhADuHHkxjyUj_v5Cd_3wMwdUl5HNNXdzvGgfVs-Ui_l)
- [Changing worldwide attitudes toward homosexuality: The influence of global and region-specific cultures, 1981–2012](https://scholar.google.com/scholar?hl=ko&as_sdt=0%2C16&q=Changing+worldwide+attitudes+toward+homosexuality%3A+The+influence+of+global+and+region-specific+cultures%2C+1981%E2%80%932012&btnG=)
- [Public Opinion About Gay Rights and Gay Marriage](https://academic.oup.com/ijpor/article/26/3/279/743213)

** dimensions 
- [Multiple Dimensions of Attitudes About Homosexuality: Development of a Multifaceted Scale Measuring Attitudes Toward Homosexuality](https://www.tandfonline.com/doi/full/10.1080/00918369.2010.517069) 

** diffusion 
- [Queer diffusions](https://journals.sagepub.com/doi/pdf/10.1068/d360?casa_token=YSHze9dAz7YAAAAA:AQUiM5dnsTNOqIYzHIoWWIHMeuvOueM1Yg7vMtHgBhsLz6KuELidtYlxlTbHEhBbAwMTpj7RmwZb). 
- [Decentering queer globalization: diffusion and the `global gay'](https://journals.sagepub.com/doi/pdf/10.1068/d63j?casa_token=0JRLZAC6tgYAAAAA:ZHZdrVNdjsbNFum7huhPu_9Zz3iPlgJ78K5ha7ReCNLrJSFoliosk-uwDQiQXvx0b-9OKDHA9Cty)
- [Mapping Changes in Attitudes towards Gays and Lesbians in Europe: An Application of Diffusion Theory](https://academic.oup.com/esr/article/38/1/124/6343126)

** related to other DCPO project?
- [Class Position and Political Opinion in Rich Democracies](https://www.diva-portal.org/smash/get/diva2:1430055/FULLTEXT01.pdf) or (https://www.annualreviews.org/doi/10.1146/annurev-soc-121919-054609)
- [Religion, Religiosity, and the Attitudes Toward Homosexuality—A Multilevel Analysis of 79 Countries](https://www.tandfonline.com/doi/full/10.1080/00918369.2014.969071)

** miscellaneous
- [Getting the Message Out: Media Context and Global Changes in Attitudes Toward Homosexuality](https://journals.sagepub.com/doi/pdf/10.1177/0010414016666836?casa_token=aS5atIDpAoUAAAAA:ftz874AYg4O9Z2IdeOXmQPPdNzL_u85B6ZNnd7oLqZp4xjdVjlGh21WVZ8S_thrbE4w6c6NG22Dn)
- [Policy Diffusion as a Geographical Expansion of the Scope of Political Conflict: Same-Sex Marriage Bans in the 1990s](https://journals.sagepub.com/doi/pdf/10.1177/153244000100100102?casa_token=bDRQx0IGCAIAAAAA:m903ukfR_QBzENH5aY765dG1Hoka1GEfgc8_n-tXPKW4NntxgK4K8s-Z1NQx3WiM1KfQfE2KDPtY)

**Comment by hey-ikon** [comment]
** notes ** 
We should be explicit about what questions we are including to create latent variable. For instance, Table 1 in [Public Attitudes toward Homosexuality and Gay Rights across Time and Countries](https://escholarship.org/content/qt4p93w90c/qt4p93w90c.pdf) there are more questions we are not including in the data -- because 'assessment of situation' and 'attitude' are different.

**Comment by fsolt** [comment]
Farther afield, but interesting (and new): [Jones, Philip Edward (2022). "Respectability Politics and Straight Support for LGB Rights." _Political Research Quarterly_, 75(4), 935–949](https://doi.org/10.1177/10659129211035834).

**Comment by fsolt** [comment]
[Girard, Tyler. (2021). "Reconciling the Theoretical and Empirical Study of International Norms: A New Approach to Measurement." _American Political Science Review_, 115(1), 331-338.](https://doi.org/10.1017/S0003055420000854)

**Comment by casstai** [comment]
Encarnación, O. G. (2022). Latin America's Abortion Rights Breakthrough. Journal of Democracy, 33(4), 89-103.
abstract: In recent years, Latin America has experienced an abortion-rights breakthrough that stands in striking contrast to the wave of criminalization of abortion afoot in the United States. It also ended some of the world's most draconian abortion bans. At the root of this breakthrough is the framing of abortion not as an issue of personal choice but as a human-rights matter. This strategy, borrowed from previous campaigns for equality and justice in Latin America—especially the struggle for same-sex marriage—capitalized on the resonance of human rights in Latin American politics and society in the postauthoritarian era.
