### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by fsolt** [fsolt/dcpo_gayrights#5]
What will we use to validate our estimates?  Internal validation is easy---we always use the most common survey item we included to create the estimates.  But construct validation is harder.  What will we use?

**Comment by fsolt** [comment]
Typically we use some survey items on some *other* topic and then some macro-level variable.

**Comment by casstai** [comment]
Winkler, S. (2021). Media's Influence on LGBTQ Support Across Africa. British Journal of Political Science, 51(2), 807-826.  
" This study develops a theory that accounts for actors' mixed approach to the media and shows how different types of media create distinct effects on public opinion of LGBTQs. Specifically, the study finds that radio and television have no, or a negative, significant effect on pro-gay attitudes, whereas individuals who consume more newspapers, internet or social media are significantly more likely to support LGBTQs "

**Comment by byngdeuk** [comment]
I also agree with Cassandra's comment.
In addition, more basically I thought that we can use the democracy index from V-Dem or Freedom House and so on.
It is based on the previous finding of the link between support for democracy and LGBT rights of the public.
For instance, the work below finds that Democracy Index is closely related to LGBT rights support.

"Earle, Megan, et al. "A multilevel analysis of LGBT (Lesbian, Gay, Bisexual, Transgender) rights support across 77 countries: The role of contact and country laws." British Journal of Social Psychology 60.3 (2021): 851-869."

**Comment by fsolt** [comment]
@Tyhcass: Interesting.  How do we operationalize this individual-level finding at the country-year level for validation purposes?

@byngdeuk Also promising.  Seems like a straightforward argument between respect for human rights and democracy.

I suppose I overlooked what I had been sort of doing already in the now-old dot-whisker plots of the latest estimates by country: changing the color of the dot to show whether marriage equality is in place.  This indicator wouldn't be great in a scatterplot (dichotomous), but we could look at some measure of policy in a bivariate way without stealing too much from our next paper.

**Comment by fsolt** [comment]
We can think about replicating (sort of) [Andersen and Fetter's 2008 AJPS](https://doi.org/10.1111/j.1540-5907.2008.00352.x): tolerance goes up with GDP and down with the Gini.  Probably not a full-blown study, but maybe as an additional validation check?  I'm not sure this relationship is sufficiently well established for failure to count against validation, though--I wouldn't be truly stunned if bringing more data shows that it doesn't hold up.  (Then maybe we write a separate piece!)  But definitely only a one-way test.

**Comment by fsolt** [comment]
@Tyhcass: Abortion attitudes?  Human rights index?  via lit on Latin America
